import { MATERIALS, SIZES_BASE } from './config.js';
import { state } from './storage.js';
import * as Physics from './physics.js';
import { refreshGold } from '/lab/shared/economy.js';

let stage, itemsEl, steamEl, spsEl, omegaEl, tempEl, pressEl, gaugeArc, toast, centerEl, goldEl; let resizeRAF=null;

function svgEl(n,a={}){const e=document.createElementNS('http://www.w3.org/2000/svg',n);for(const k in a)e.setAttribute(k,a[k]);return e;}
function ensureDefs(){let d=stage.querySelector('defs');if(!d){d=svgEl('defs');stage.appendChild(d);}return d;}
function tierColors(base,t){const mat=MATERIALS[base]||MATERIALS.steel;const map={steel:'copper',copper:'bronze',bronze:'brass',brass:'gold',gold:'titanium',titanium:'aether',aether:'aether'};if(t===2)return MATERIALS[map[base]]||mat;return mat;}
function gearPath(cx,cy,r,te){const p=svgEl('path',{fill:'#1e140c'});const th=(Math.PI*2)/te;const tooth=th*0.6;const gap=th-tooth;let d='';for(let i=0;i<te;i++){const a=i*th,a2=a+tooth,aM=a+tooth/2;const x1=cx+Math.cos(a)*r,y1=cy+Math.sin(a)*r;const x2=cx+Math.cos(a2)*r,y2=cy+Math.sin(a2)*r;const xg=cx+Math.cos(a2+gap)*r,yg=cy+Math.sin(a2+gap)*r;const xM=cx+Math.cos(aM)*(r+r*0.16),yM=cy+Math.sin(aM)*(r+r*0.16);d+=(i===0?`M ${x1} ${y1}`:` L ${x1} ${y1}`)+` L ${xM} ${yM} L ${x2} ${y2} L ${xg} ${yg}`}d+=' Z';p.setAttribute('d',d);p.setAttribute('stroke','#000');p.setAttribute('stroke-width',r*0.02);return p;}
function makeGear(cx,cy,r,te,c){const g=svgEl('g');const gradId='grad_'+Math.random().toString(36).slice(2);const defs=ensureDefs();const lg=svgEl('linearGradient',{id:gradId,x1:'0',y1:'0',x2:'1',y2:'1'});lg.appendChild(svgEl('stop',{offset:'0%','stop-color':c[0]}));lg.appendChild(svgEl('stop',{offset:'60%','stop-color':c[1]}));lg.appendChild(svgEl('stop',{offset:'100%','stop-color':c[2]}));defs.appendChild(lg);const toothed=gearPath(cx,cy,r,te);const face=svgEl('circle',{cx,cy,r:r*0.6,fill:`url(#${gradId})`,stroke:'#2a1b0f','stroke-width':r*0.08});g.appendChild(toothed);g.appendChild(face);g.appendChild(svgEl('circle',{cx,cy,r:r*0.1,fill:'#24160c',stroke:'#000','stroke-width':r*0.04}));return g;}
function metrics(){const r=stage.getBoundingClientRect();const w=r.width,h=r.height;const m=Math.min(w,h);const gap=Math.max(36,Math.floor(m*0.06));const mainR=Math.max(90,Math.min(160,Math.floor(m*0.22)));return {w,h,cx:w/2,cy:h/2+6,mainR,gap};}
let M=null;
export function init(){stage=document.getElementById('stage');itemsEl=document.getElementById('items');steamEl=document.getElementById('steamCount');goldEl=document.getElementById('goldCount');spsEl=document.getElementById('spsText');omegaEl=document.getElementById('omegaText');tempEl=document.getElementById('tempText');pressEl=document.getElementById('pressText');gaugeArc=document.getElementById('gaugeArc');toast=document.getElementById('toast');buildStage();placeRingGears();}
export function relayoutSmooth(){if(resizeRAF)cancelAnimationFrame(resizeRAF);resizeRAF=requestAnimationFrame(()=>{const prev=stage._center?{...stage._center}:null;buildStage();placeRingGears();if(prev){const dx=(prev.cx-stage._center.cx),dy=(prev.cy-stage._center.cy);stage.style.transform=`translate(${dx}px,${dy}px)`;requestAnimationFrame(()=>stage.style.transform='translate(0,0)');}});}
function setVB(){const r=stage.getBoundingClientRect();stage.setAttribute('viewBox',`0 0 ${r.width} ${r.height}`);}
function buildStage(){stage.innerHTML='';setVB();M=metrics();const cx=M.cx,cy=M.cy;const defs=ensureDefs();const wood=svgEl('radialGradient',{id:'woodTex',cx:'50%',cy:'50%'});wood.appendChild(svgEl('stop',{offset:'0%','stop-color':'#3a2718'}));wood.appendChild(svgEl('stop',{offset:'50%','stop-color':'#2b1d12'}));wood.appendChild(svgEl('stop',{offset:'100%','stop-color':'#1e140d'}));defs.appendChild(wood);stage.appendChild(svgEl('circle',{cx,cy,r:M.mainR+M.gap*5+90,fill:'url(#woodTex)'}));const main=makeGear(cx,cy,M.mainR,28,tierColors('brass',2));main.style.transformOrigin=`${cx}px ${cy}px`;stage.appendChild(main);stage._main=main;stage._center={cx,cy};stage._mainR=M.mainR;stage._ringGap=M.gap;stage._connLayer=svgEl('g');stage.appendChild(stage._connLayer);stage._rings=[];stage._chains=[];for(let i=0;i<5;i++){const g=svgEl('g');stage.appendChild(g);stage._rings.push(g);const ch=svgEl('g');stage.appendChild(ch);stage._chains.push(ch);}stage.appendChild(svgEl('ellipse',{cx,cy:cy-20,rx:M.mainR+M.gap*5+60,ry:M.mainR+M.gap*5-10,fill:'rgba(255,255,255,0.02)'}));}
export function placeRingGears(){const {cx,cy}=stage._center;stage._connLayer.innerHTML='';stage._chains.forEach(g=>g.innerHTML='');stage._rings.forEach(g=>g.innerHTML='');const sizeScale=Math.max(0.8,Math.min(1.3,M.mainR/120));const ids=['gear','drone','auto','boiler','aether'];ids.forEach((id,idx)=>{const r=state.rings[id];const ringR=stage._mainR+stage._ringGap*(idx+1);const base=SIZES_BASE[idx];const size=base*sizeScale;const g=stage._rings[idx];const colors=tierColors(['steel','copper','bronze','brass','aether'][idx],1);if(r.chain){const ch=stage._chains[idx];const c=svgEl('circle',{cx,cy,r:ringR,fill:'none',stroke:colors[1],'stroke-width':size*0.4,'stroke-dasharray':'18 18','stroke-linecap':'round',opacity:0.85});ch.appendChild(c);ch._circle=c;}else{const total=r.t1+r.t2;const start=state.offsets[idx];const angles=[];for(let i=0;i<total;i++){const a=start+(360/Math.max(total,1))*i;angles.push(a);const rad=a*Math.PI/180;const x=cx+ringR*Math.cos(rad),y=cy+ringR*Math.sin(rad);const tier=(i<r.t2)?2:1;const gear=makeGear(x,y,tier===2?size*1.1:size,10+idx*2+(tier===2?2:0),tierColors(['steel','copper','bronze','brass','aether'][idx],tier));gear.style.transformOrigin=`${x}px ${y}px`;g.appendChild(gear);}g._angles=angles;}});for(let k=1;k<5;k++){const prev=stage._rings[k-1];const curr=stage._rings[k];const angPrev=prev._angles||[];const angThis=curr._angles||[];const tol=180/Math.max(angThis.length||1,(angPrev.length?angPrev.length*2:1));for(const a of angThis){let nearest=null,best=999;for(const b of angPrev){const d=Math.abs(((a-b+540)%360)-180);if(d<best){best=d;nearest=b;}}if(nearest!==null){const rIn=stage._mainR+stage._ringGap*(k),rOut=stage._mainR+stage._ringGap*(k+1);const ra=a*Math.PI/180,rb=nearest*Math.PI/180;const x1=stage._center.cx+rOut*Math.cos(ra),y1=stage._center.cy+rOut*Math.sin(ra);const x2=stage._center.cx+rIn*Math.cos(rb),y2=stage._center.cy+rIn*Math.sin(rb);const ok=best<=tol;const line=svgEl('line',{x1,y1,x2,y2,stroke:ok?'#9ad484':'#d48a8a','stroke-width':3,opacity:ok?.6:.25});stage._connLayer.appendChild(line);}}}
export function bindMainGearClick(cb){stage._main?.addEventListener('click',cb);}
export function bindWheel(handler){const center=document.getElementById('center');center.addEventListener('wheel',(e)=>{e.preventDefault();const delta=Math.sign(-e.deltaY);const mag=Math.min(3,Math.abs(e.deltaY)/120);handler(delta,mag,e.ctrlKey);},{passive:false});}
export function sparkIfReverse(){if(state.omega<-200){const s=document.createElement('div');s.className='negSpark';s.style.left='50%';s.style.top='50%';s.style.setProperty('--dx',(Math.random()*120-60)+'px');s.style.setProperty('--dy',(-40-Math.random()*60)+'px');stage.parentElement.appendChild(s);setTimeout(()=>s.remove(),600);}}
export function updateHUD({sps}){function fmt(n){if(n<1000)return n.toFixed(0);const u=['','K','M','B','T'];let i=0;while(n>=1000&&i<u.length-1){n/=1000;i++;}return n.toFixed(2)+u[i];}document.getElementById('steamCount').textContent=fmt(state.steam);document.getElementById('spsText').textContent=(sps||0).toFixed(2);document.getElementById('omegaText').textContent=state.omega.toFixed(1);document.getElementById('tempText').textContent=state.temperature.toFixed(1);document.getElementById('pressText').textContent=state.pressure.toFixed(1);const pct=Math.min(1,Math.abs(state.omega)/1600);const ang=pct*Math.PI;const x=12+46-46*Math.cos(ang),y=38-46*Math.sin(ang);document.getElementById('gaugeArc').setAttribute('d',`M12,38 A46,46 0 0,1 ${x.toFixed(2)},${y.toFixed(2)}`);}
export function spinRings(now){const ids=['gear','drone','auto','boiler','aether'];ids.forEach((id,i)=>{const g=stage._rings[i];if(!g)return;const n=g.children.length;const dir=(i%2===0?1:-1);for(let k=0;k<n;k++){const child=g.children[k];const speed=(1+i*0.5+(k/n)*0.6)*40;const angle=(now/1000)*speed*dir;child.style.transform=`rotate(${angle}deg)`;}const ch=stage._chains[i];if(ch&&ch._circle){const off=(now/1000)*160*(state.omega>=0?1:-1);ch._circle.style.strokeDashoffset=off;}});}
export async function refreshGoldHUD(){const g=await refreshGold();const ge=document.getElementById('goldCount');if(ge)ge.textContent=g;}
export function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1200);}
export { buildStage, placeRingGears };